use mayandb;
drop table Link_Item_Foto;
drop table Link_Negozio_Foto;
drop table Link_Negozio_Item;
drop table Link_Rec_Item;
drop table Allegato;
drop table Visual;
drop table Recensione;
drop table Messaggio;
drop table Acquisto;
drop table Item;
drop table Foto;
drop table Negozio;
drop table Location;
drop table Citta;
drop table User;